version: '3.7'

services:

  frontend:
    container_name: frontend
    build: ./
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:8080
    command: npm start
    networks:
      - debitmanagement

networks:
  debitmanagement:
    name: debit_management_network
    external: true
    